language: php
php:
#  - 7.0
#  - 7.1
  - 7.2
#  - 5.6
services:
  - mysql

cache:
  directories:
  - $HOME/.composer/cache

install:
  - composer --version
  - composer install -n
  - bash ./prepare_magento.sh
  - php .travis/import_categories.php
  - php .travis/import_products.php

script:
  - ./vendor/bin/phpunit
  - bash ./run_tests.sh;
