language: php
php:
#  - 7.0
#  - 7.1
  - 7.2
#  - 5.6

sudo: false

cache:
  directories:
  - $HOME/.composer/cache

install:
  - composer --version
  - composer install -n
  - bash ./prepare_magento.sh

script:
  - ./run_tests.sh;
