language: php
php:
#  - 7.0
#  - 7.1
  - 7.2
#  - 5.6
services:
  - mysql

cache:
  directories:
  - $HOME/.composer/cache
  - ./magento

install:
  - composer --version
  - composer install -n
  - bash ./prepare_magento.sh

script:
  - bash ./run_tests.sh;
