language: php
php:
#  - 7.0
#  - 7.1
  - 7.2
#  - 5.6

env:
  global:
  - MAGENTO_REPOSITORY="https://github.com/OpenMage/magento-lts.git"
  - MAGENTO_REPOSITORY_BRANCH="1.9.3.x"
  matrix:
  - MAGENTO_REPOSITORY="https://github.com/OpenMage/magento-mirror.git" MAGENTO_REPOSITORY_BRANCH="magento-1.9"

services:
  - mysql

cache:
  directories:
  - $HOME/.composer/cache

install:
  - composer --version
  - composer install -n
  - bash ./prepare_magento.sh
  - php .travis/import_categories.php
  - php .travis/import_products.php
  - ./vendor/bin/n98-magerun --root-dir=magento/ index:reindex:all

script:
  - ./vendor/bin/phpunit
  - bash ./run_tests.sh;
